site_name: Physics and Mathematics
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
  code:
    highlighting: true
    language: python
  palette:
    primary: teal
markdown_extensions:
  - toc
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mermaid2

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

    